name: Continuous Integration

on:
  push:
    branches: master
  pull_request:

jobs:
#========================================================================================  
  frontend:
    name: CI Frontend
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('CoronaFrontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-  

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Dependencies
      run: npm install --prefix CoronaFrontend

    - name: Build
      run: npm run build --prefix CoronaFrontend
#======================================================================================== 
  backend:
    name: CI Backend
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Compile
      run: mvn compile --file CoronaBackend/pom.xml

    - name: Test
      run: mvn test --file CoronaBackend/pom.xml

